### ISSUE TITLE
DenseNet ceil_mode error

### ISSUE THREAD

**Issue by ldfinfontainebleau** [wdjang/BRS-Interactive_segmentation#1]
Thank you for your job! When I run this project I found your deploy.prototxt use ceil_mode which has been replaced by round_mode in Caffe now.

**Comment by ldfinfontainebleau** [comment]
deploy.prototxt
```
# 93    ceil_mode: false
```
change into 
```
# round_mode: 1
```
seems work.

**Comment by wdjang** [comment]
Thanks for pointing it out!
